ALLOWED_TRANSITIONS = {
 "CASE_CREATED": {"DOCUMENTS_COLLECTING"},
 "DOCUMENTS_COLLECTING": {"DOCUMENTS_PROCESSING", "ACTION_REQUIRED"},
 "ACTION_REQUIRED": {"DOCUMENTS_COLLECTING", "READY_FOR_SUBMISSION"},
 "READY_FOR_SUBMISSION": {"USER_REVIEW_REQUIRED"},
 "USER_REVIEW_REQUIRED": {"CLAIM_SUBMITTED"},
 "CLAIM_SUBMITTED": {"INSURER_REVIEW"}
}
def can_transition(current: str, target: str) -> bool:
    return target in ALLOWED_TRANSITIONS.get(current, set())
